### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by tillkruss** [h2non/imaginary#171]
I'm getting the following error message:

```json
{"message":"Method not allowed","code":2}
```

For this request:

```
http://127.0.0.1:8088/crop?width=500&height=200&gravity=smart&url=https://raw.githubusercontent.com/h2non/imaginary/master/fixtures/smart-crop.jpg
```

This is how my `docker-compose.yml` file looks:

```yaml
  imaginary:
    image: h2non/imaginary
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
    command: imaginary -concurrency 50 -enable-url-source
```

What am I doing wrong?

**Comment by mpartipilo** [comment]
Try adding -cors to the command.

**Comment by h2non** [comment]
Because of the Dockerfile `ENTRYPOINT` directive, from `compose` just use: 
```yaml
  imaginary:
    image: h2non/imaginary
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
    command: -concurrency 50 -enable-url-source
```
