### ISSUE TITLE
Kubernetes pod restart loop since upgrade to 1.0.17

### ISSUE THREAD

**Issue by davemason-ladbible** [h2non/imaginary#244]
We've been running Imaginary as a replica set in our GCloud Kubernetes cluster for a while now. We found an issue with certain large images that appeared to be fixed by upgrading to 1.0.17 (testing and confirmed by running as containers locally).

However, when we attempt to upgrade the replica set on Kubernetes, the pods get stuck in a restart loop.

We have managed to spot an error along the lines of the `/bin/imaginary` execution file not existing.

I've been through the release notes for 1.0.17 but I can't see anything in there that would cause this to suddenly stop working.

For reference, here's the YALM for the replica-set:

```yaml
replicaCount: 1
maxReplicaCount: 2

image:
  repository: h2non/imaginary
  tag: 1.0.17
  pullPolicy: Always
  workingDir: /app

resources:
  limits:
    memory: 2Gi
    cpu: 1

commands:
  - /bin/imaginary
  - -concurrency
  - "10"
  - -http-cache-ttl
  - "604800"
  - -enable-url-source
  - -allowed-origins
  - "[REDACTED]"

nameOverride: images

containerPort: 9000

service:
  type: LoadBalancer
  port: 80
  targetPort: 9000

envs:
  - name: VIPS_CONCURRENCY
    value: 10
```

Any pointers you can provide would be greatly appreciated, as I'm keen to get this upgrade done and I've been scratching my head on this one for a while now.

Thanks.

**Comment by davemason-ladbible** [comment]
Sorry, figured this one out myself.

On the off-chance anyone hits the same issue, the first arg didn't need to be `/bin/imaginary`. `imaginary` works fine. I'm guessing that the location of the executable has changed in 1.0.17, but if we'd been calling it properly in the first place this wouldn't have been a breaking change.

**Comment by Dynom** [comment]
Hi @davemason-ladbible, thanks for providing feedback.

I'm not sure if the binary path actually changed with 1.0.17, however I don't think you need to specify the binary at all. The Dockerfile declares an [`ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#entrypoint) with the path to the binary, unless you override the ENTRYPOINT (which I don't recommend!) you can just leave it out.

```sh
$ docker run --rm -it -e "PORT=9000" -p 9000:9000 h2non/imaginary:1.0.17 -- --enable-url-source
172.17.0.1 - - [28/Jan/2019 08:58:11] "GET /pipeline?url=https://pbs.twimg.com/media/DwX-vRdUYAACZ0x.jpg&operations=%5B%7B%22operation%22%3A%22resize%22%2C%22params%22%3A%7B%22quality%22%3A70%2C%22noprofile%22%3Atrue%2C%22stripmeta%22%3Atrue%2C%22nocrop%22%3Atrue%2C%22width%22%3A865%7D%7D%5D HTTP/1.1" 405 41 0.0028
```

I'm not familiar with the syntax you're using. Do you use k8s? My RecordSet looks more along the lines of:
```
    spec:
      containers:
      - args:
        - -enable-url-source
        - -http-read-timeout=10
        - -http-cache-ttl=31536000
        - ...
        image: h2non/imaginary:1.0.17
        imagePullPolicy: IfNotPresent
        name: imaginary
      ...
```
