### ISSUE TITLE
locally installed self signed certificates

### ISSUE THREAD

**Issue by djkato** [h2non/imaginary#439]
edit: 
As I was writing this it suddenly started working and I got mad, but this means I solved it, so I'll just post for future reference here for others and myself.

Hello, 
In order to use this in my stack in dev, I need to use locally signed certificates.
There is no way I found that allows imaginary to use locally (in the container) installed root certificates.
I run my dev stack behind caddy locally with a cert I signed inside caddy, then copied out and made persistent.

`docker-compose.yml`
```yml
services:
    caddy:
        container_name: caddy
        hostname: caddy
        image: ghcr.io/djkato/caddy-docker-proxy-cloudflare:2.9.1
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=saleor-marketplace_caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./temp/caddy:/data
            - ./temp/pki:/pki
        restart: unless-stopped
        labels:
            caddy.debug: ""
            caddy.local_certs: ""
            caddy.pki.ca: "local"
            caddy.pki.ca.root.cert: "/pki/caddy-local-root.crt"
            caddy.pki.ca.root.key: "/pki/caddy-local-root.key"

    garage:
        image: dxflrs/garage:v2.0.0
        env_file: .env
        restart: unless-stopped
        volumes:
            - ./garage.toml:/etc/garage.toml
            - ./temp/garage/meta:/g/meta
            - ./temp/garage/data:/g/data
        networks:
            - caddy
            - backend
        labels:
            caddy: "cdn.harbour.de"
            caddy.reverse_proxy: "{{upstreams 3902}}"
            caddy_1: "s3.harbour.de"
            caddy_1.reverse_proxy: "{{upstreams 3900}}"

    imaginary:
        image: h2non/imaginary:latest
        env_file: .env #url-signature is defined here
        volumes:
            - ./temp/pki:/pki
            - ./temp/imaginary:/mnt/data
        command:
            -enable-url-source -forward-headers -enable-url-signature -max-allowed-size 15000000 -enable-placeholder -concurrency 20 -mount /mnt/data
        networks:
            - caddy
        extra_hosts:
            cdn.harbour.de: 10.0.0.19
        labels:
            caddy: "imaginary.harbour.de"
            caddy.reverse_proxy: "{{upstreams 9000}}"

networks:
    caddy:
```
Here are my scripts to install the local certificates inside the imaginary container. I run these every time before `docker compose up`:
```sh
#!/bin/bash
docker compose up -d imaginary
docker compose exec -it -u root imaginary apt update
docker compose exec -it -u root imaginary apt install ca-certificates curl -y
docker compose exec -it -u root imaginary cp /pki/caddy-local-root.crt /usr/local/share/ca-certificates/
docker compose exec -it -u root imaginary cp /pki/caddy-local-root.crt /usr/local/share/ca-certificates/
docker compose exec -it -u root imaginary update-ca-certificates
```
Before these curl doesn't work, but after, Curl inside the container works just fine, meaning I installed them correctly:
![Image](https://github.com/user-attachments/assets/e860a21a-1bc5-4aa8-a6ac-f0c76636a204)

thanks
